### PR TITLE
fix: pass method to fetcher submit options

### PR DESCRIPTION
**Pull request by gregermendle**
It looks like the method prop is not being passed down to the `fetcher.submit` call in `<ValidatedForm />`. This should fix that.

### CODE REVIEW

**Comment by airjp73** [comment]
Hi! Thanks for doing this. Could you add a test as well?

**Comment by gregermendle** [comment]
> Hi! Thanks for doing this. Could you add a test as well?

Updated with an additional test, lmk if I should add some additional ones.

**Comment by airjp73** [comment]
Looks good. Thanks!

**Comment by airjp73** [comment]
Published as v4.6.9

**Pull request merged**
