### PR TITLE
Add test case for setting controlled field value on mount

### PR DESCRIPTION
**Pull request by danecando**
This is the occasional field tracking example as a test case: https://www.remix-validated-form.io/reference/use-control-field

See #123

### CODE REVIEW

**Comment by danecando** [comment]
Probably should have asked how you wanted this since the fix is on another branch

**Comment by airjp73** [comment]
Looks good!

Sorry I've been slow in responding to this. If you're able to rebase this on the `fieldarray` branch that would be the most ideal, I think. Then I can merge it right in.

**Review by airjp73 — CHANGES_REQUESTED** [review]
If we rebase this onto `fieldarray`, then we can get this merged in now. If you don't have time, I'll merge it after I finish and merge that branch (hopefully this week or next week).

**Comment by danecando** [comment]
done

**Pull request merged**
