### PR TITLE
feat: support remix v1.6.5 `TypeResponse`

### LINKED ISSUE #140: [Feature]: Support Remix 1.6.5 `useActionData/useLoaderData` type inference
### What is the new or updated feature that you are suggesting?

With the new Remix 1.6.5, both `useActionData` & `useLoaderData` will now able to infer the response type. However, due to the fact that `remix-validated-form` still relies on the type from remix v1.2.X, remix type inference will not able to work properly.

For example:
```tsx
import {ValidatedForm, validationError} from 'remix-validated-form';
import {withZod} from '@remix-validated-form/with-zod';

const formValidator = withZod(/** ... */);

export const action = async ({request}: ActionArgs) => {
  const formData = await request.formData();
  const data = await formValidator.validate(formData);
  if (data.error) return validationError(data.error);
  return json('Some data...');
};

const Index = () => {
  const actionData = useActionData<typeof action>();
  //    ^ This will always return `any` type
  return <ValidatedForm ...>...</ValidatedForm>
}
```

Reference: https://github.com/remix-run/remix/pull/3276

### Why should this feature be included?

As people who use this `remix-validated-form` as their form validation management library will not be able to get the latest type-support from Remix. Else the only workaround is to patch the typing in the package manually.

### PR DESCRIPTION
**Pull request by chungweileong94**
fix #140

### CODE REVIEW

**Comment by chungweileong94** [comment]
I'm not sure if I need to update the remix version for the sample/test-app, it does work for v1.2.1.

**Comment by airjp73** [comment]
The failing test is unrelated so I'm just going to merge. Thanks for the help!

**Comment by chungweileong94** [comment]
> The failing test is unrelated so I'm just going to merge. Thanks for the help!

Oh cool, I was figuring out why, but thx👍

**Comment by airjp73** [comment]
If you do figure it out, I'll happily accept the fix! But don't feel obligated :)

**Pull request merged**
